# coding: utf-8

# flake8: noqa

"""
    Kimai 2 - API Docs

    JSON API for the Kimai 2 time-tracking software. Read more about its usage in the [API documentation](https://www.kimai.org/documentation/rest-api.html) and then download a [Swagger file](doc.json) for import e.g. in Postman. Be aware: it is not yet considered stable and BC breaks might happen, but we try to avoid them.   # noqa: E501

    OpenAPI spec version: 0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from kimai_client.api.default_api import DefaultApi

# import ApiClient
from kimai_client.api_client import ApiClient
from kimai_client.configuration import Configuration
# import models into sdk package
from kimai_client.models.activity import Activity
from kimai_client.models.activity_collection import ActivityCollection
from kimai_client.models.activity_edit_form import ActivityEditForm
from kimai_client.models.activity_entity import ActivityEntity
from kimai_client.models.activity_meta import ActivityMeta
from kimai_client.models.activity_meta_field import ActivityMetaField
from kimai_client.models.body import Body
from kimai_client.models.body1 import Body1
from kimai_client.models.body2 import Body2
from kimai_client.models.body3 import Body3
from kimai_client.models.body4 import Body4
from kimai_client.models.customer import Customer
from kimai_client.models.customer2 import Customer2
from kimai_client.models.customer_collection import CustomerCollection
from kimai_client.models.customer_edit_form import CustomerEditForm
from kimai_client.models.customer_entity import CustomerEntity
from kimai_client.models.customer_meta import CustomerMeta
from kimai_client.models.customer_meta_field import CustomerMetaField
from kimai_client.models.i18n_config import I18nConfig
from kimai_client.models.project import Project
from kimai_client.models.project2 import Project2
from kimai_client.models.project_collection import ProjectCollection
from kimai_client.models.project_edit_form import ProjectEditForm
from kimai_client.models.project_entity import ProjectEntity
from kimai_client.models.project_meta import ProjectMeta
from kimai_client.models.project_meta_field import ProjectMetaField
from kimai_client.models.tag_edit_form import TagEditForm
from kimai_client.models.tag_entity import TagEntity
from kimai_client.models.team import Team
from kimai_client.models.team2 import Team2
from kimai_client.models.team3 import Team3
from kimai_client.models.team4 import Team4
from kimai_client.models.team5 import Team5
from kimai_client.models.team_collection import TeamCollection
from kimai_client.models.team_edit_form import TeamEditForm
from kimai_client.models.team_entity import TeamEntity
from kimai_client.models.timesheet import Timesheet
from kimai_client.models.timesheet_collection import TimesheetCollection
from kimai_client.models.timesheet_config import TimesheetConfig
from kimai_client.models.timesheet_edit_form import TimesheetEditForm
from kimai_client.models.timesheet_entity import TimesheetEntity
from kimai_client.models.timesheet_meta import TimesheetMeta
from kimai_client.models.timesheet_meta2 import TimesheetMeta2
from kimai_client.models.timesheet_sub_collection import TimesheetSubCollection
from kimai_client.models.user import User
from kimai_client.models.user_collection import UserCollection
from kimai_client.models.user_create_form import UserCreateForm
from kimai_client.models.user_edit_form import UserEditForm
from kimai_client.models.user_entity import UserEntity
from kimai_client.models.version import Version
