# coding: utf-8

"""
    Kimai 2 - API Docs

    JSON API for the Kimai 2 time-tracking software. Read more about its usage in the [API documentation](https://www.kimai.org/documentation/rest-api.html) and then download a [Swagger file](doc.json) for import e.g. in Postman. Be aware: it is not yet considered stable and BC breaks might happen, but we try to avoid them.   # noqa: E501

    OpenAPI spec version: 0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kimai_client
from kimai_client.api.default_api import DefaultApi  # noqa: E501
from kimai_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = kimai_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_activities_get(self):
        """Test case for api_activities_get

        Returns a collection of activities  # noqa: E501
        """
        pass

    def test_api_activities_id_get(self):
        """Test case for api_activities_id_get

        Returns one activity  # noqa: E501
        """
        pass

    def test_api_activities_id_meta_patch(self):
        """Test case for api_activities_id_meta_patch

        Sets the value of a meta-field for an existing activity.  # noqa: E501
        """
        pass

    def test_api_activities_id_patch(self):
        """Test case for api_activities_id_patch

        Update an existing activity  # noqa: E501
        """
        pass

    def test_api_activities_post(self):
        """Test case for api_activities_post

        Creates a new activity  # noqa: E501
        """
        pass

    def test_api_config_i18n_get(self):
        """Test case for api_config_i18n_get

        Returns the user specific locale configuration  # noqa: E501
        """
        pass

    def test_api_config_timesheet_get(self):
        """Test case for api_config_timesheet_get

        Returns the instance specific timesheet configuration  # noqa: E501
        """
        pass

    def test_api_customers_get(self):
        """Test case for api_customers_get

        Returns a collection of customers  # noqa: E501
        """
        pass

    def test_api_customers_id_get(self):
        """Test case for api_customers_id_get

        Returns one customer  # noqa: E501
        """
        pass

    def test_api_customers_id_meta_patch(self):
        """Test case for api_customers_id_meta_patch

        Sets the value of a meta-field for an existing customer.  # noqa: E501
        """
        pass

    def test_api_customers_id_patch(self):
        """Test case for api_customers_id_patch

        Update an existing customer  # noqa: E501
        """
        pass

    def test_api_customers_post(self):
        """Test case for api_customers_post

        Creates a new customer  # noqa: E501
        """
        pass

    def test_api_ping_get(self):
        """Test case for api_ping_get

        A testing route for the API  # noqa: E501
        """
        pass

    def test_api_projects_get(self):
        """Test case for api_projects_get

        Returns a collection of projects.  # noqa: E501
        """
        pass

    def test_api_projects_id_get(self):
        """Test case for api_projects_id_get

        Returns one project  # noqa: E501
        """
        pass

    def test_api_projects_id_meta_patch(self):
        """Test case for api_projects_id_meta_patch

        Sets the value of a meta-field for an existing project.  # noqa: E501
        """
        pass

    def test_api_projects_id_patch(self):
        """Test case for api_projects_id_patch

        Update an existing project  # noqa: E501
        """
        pass

    def test_api_projects_post(self):
        """Test case for api_projects_post

        Creates a new project  # noqa: E501
        """
        pass

    def test_api_tags_get(self):
        """Test case for api_tags_get

        Fetch all existing tags  # noqa: E501
        """
        pass

    def test_api_tags_id_delete(self):
        """Test case for api_tags_id_delete

        Delete a tag  # noqa: E501
        """
        pass

    def test_api_tags_post(self):
        """Test case for api_tags_post

        Creates a new tag  # noqa: E501
        """
        pass

    def test_api_teams_get(self):
        """Test case for api_teams_get

        Fetch all existing teams  # noqa: E501
        """
        pass

    def test_api_teams_id_customers_customer_id_delete(self):
        """Test case for api_teams_id_customers_customer_id_delete

        Revokes access for a customer from a team  # noqa: E501
        """
        pass

    def test_api_teams_id_customers_customer_id_post(self):
        """Test case for api_teams_id_customers_customer_id_post

        Grant the team access to a customer  # noqa: E501
        """
        pass

    def test_api_teams_id_delete(self):
        """Test case for api_teams_id_delete

        Delete a team  # noqa: E501
        """
        pass

    def test_api_teams_id_get(self):
        """Test case for api_teams_id_get

        Returns one team  # noqa: E501
        """
        pass

    def test_api_teams_id_members_user_id_delete(self):
        """Test case for api_teams_id_members_user_id_delete

        Removes a member from the team  # noqa: E501
        """
        pass

    def test_api_teams_id_members_user_id_post(self):
        """Test case for api_teams_id_members_user_id_post

        Add a new member to a team  # noqa: E501
        """
        pass

    def test_api_teams_id_patch(self):
        """Test case for api_teams_id_patch

        Update an existing team  # noqa: E501
        """
        pass

    def test_api_teams_id_projects_project_id_delete(self):
        """Test case for api_teams_id_projects_project_id_delete

        Revokes access for a project from a team  # noqa: E501
        """
        pass

    def test_api_teams_id_projects_project_id_post(self):
        """Test case for api_teams_id_projects_project_id_post

        Grant the team access to a project  # noqa: E501
        """
        pass

    def test_api_teams_post(self):
        """Test case for api_teams_post

        Creates a new team  # noqa: E501
        """
        pass

    def test_api_timesheets_active_get(self):
        """Test case for api_timesheets_active_get

        Returns the collection of active timesheet records  # noqa: E501
        """
        pass

    def test_api_timesheets_get(self):
        """Test case for api_timesheets_get

        Returns a collection of timesheet records  # noqa: E501
        """
        pass

    def test_api_timesheets_id_delete(self):
        """Test case for api_timesheets_id_delete

        Delete an existing timesheet record  # noqa: E501
        """
        pass

    def test_api_timesheets_id_export_patch(self):
        """Test case for api_timesheets_id_export_patch

        Switch the export state of a timesheet record to (un-)lock it  # noqa: E501
        """
        pass

    def test_api_timesheets_id_get(self):
        """Test case for api_timesheets_id_get

        Returns one timesheet record  # noqa: E501
        """
        pass

    def test_api_timesheets_id_meta_patch(self):
        """Test case for api_timesheets_id_meta_patch

        Sets the value of a meta-field for an existing timesheet.  # noqa: E501
        """
        pass

    def test_api_timesheets_id_patch(self):
        """Test case for api_timesheets_id_patch

        Update an existing timesheet record  # noqa: E501
        """
        pass

    def test_api_timesheets_id_restart_patch(self):
        """Test case for api_timesheets_id_restart_patch

        Restarts a previously stopped timesheet record for the current user  # noqa: E501
        """
        pass

    def test_api_timesheets_id_stop_patch(self):
        """Test case for api_timesheets_id_stop_patch

        Stops an active timesheet record  # noqa: E501
        """
        pass

    def test_api_timesheets_post(self):
        """Test case for api_timesheets_post

        Creates a new timesheet record  # noqa: E501
        """
        pass

    def test_api_timesheets_recent_get(self):
        """Test case for api_timesheets_recent_get

        Returns the collection of recent user activities  # noqa: E501
        """
        pass

    def test_api_users_get(self):
        """Test case for api_users_get

        Returns the collection of all registered users  # noqa: E501
        """
        pass

    def test_api_users_id_get(self):
        """Test case for api_users_id_get

        Return one user entity  # noqa: E501
        """
        pass

    def test_api_users_id_patch(self):
        """Test case for api_users_id_patch

        Update an existing user  # noqa: E501
        """
        pass

    def test_api_users_me_get(self):
        """Test case for api_users_me_get

        Return the current user entity  # noqa: E501
        """
        pass

    def test_api_users_post(self):
        """Test case for api_users_post

        Creates a new user  # noqa: E501
        """
        pass

    def test_api_version_get(self):
        """Test case for api_version_get

        Returns information about the Kimai release  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
