# coding: utf-8

"""
    Kimai 2 - API Docs

    JSON API for the Kimai 2 time-tracking software. Read more about its usage in the [API documentation](https://www.kimai.org/documentation/rest-api.html) and then download a [Swagger file](doc.json) for import e.g. in Postman. Be aware: it is not yet considered stable and BC breaks might happen.   # noqa: E501

    OpenAPI spec version: 0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CustomerEditForm(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'number': 'str',
        'comment': 'str',
        'company': 'str',
        'vat_id': 'str',
        'contact': 'str',
        'address': 'str',
        'country': 'str',
        'currency': 'str',
        'phone': 'str',
        'fax': 'str',
        'mobile': 'str',
        'email': 'str',
        'homepage': 'str',
        'timezone': 'str',
        'color': 'str',
        'visible': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'number': 'number',
        'comment': 'comment',
        'company': 'company',
        'vat_id': 'vatId',
        'contact': 'contact',
        'address': 'address',
        'country': 'country',
        'currency': 'currency',
        'phone': 'phone',
        'fax': 'fax',
        'mobile': 'mobile',
        'email': 'email',
        'homepage': 'homepage',
        'timezone': 'timezone',
        'color': 'color',
        'visible': 'visible'
    }

    def __init__(self, name=None, number=None, comment=None, company=None, vat_id=None, contact=None, address=None, country=None, currency=None, phone=None, fax=None, mobile=None, email=None, homepage=None, timezone=None, color=None, visible=None):  # noqa: E501
        """CustomerEditForm - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._number = None
        self._comment = None
        self._company = None
        self._vat_id = None
        self._contact = None
        self._address = None
        self._country = None
        self._currency = None
        self._phone = None
        self._fax = None
        self._mobile = None
        self._email = None
        self._homepage = None
        self._timezone = None
        self._color = None
        self._visible = None
        self.discriminator = None

        self.name = name
        if number is not None:
            self.number = number
        if comment is not None:
            self.comment = comment
        if company is not None:
            self.company = company
        if vat_id is not None:
            self.vat_id = vat_id
        if contact is not None:
            self.contact = contact
        if address is not None:
            self.address = address
        self.country = country
        self.currency = currency
        if phone is not None:
            self.phone = phone
        if fax is not None:
            self.fax = fax
        if mobile is not None:
            self.mobile = mobile
        if email is not None:
            self.email = email
        if homepage is not None:
            self.homepage = homepage
        self.timezone = timezone
        self.color = color
        if visible is not None:
            self.visible = visible

    @property
    def name(self):
        """Gets the name of this CustomerEditForm.  # noqa: E501


        :return: The name of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomerEditForm.


        :param name: The name of this CustomerEditForm.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def number(self):
        """Gets the number of this CustomerEditForm.  # noqa: E501


        :return: The number of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this CustomerEditForm.


        :param number: The number of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def comment(self):
        """Gets the comment of this CustomerEditForm.  # noqa: E501


        :return: The comment of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this CustomerEditForm.


        :param comment: The comment of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def company(self):
        """Gets the company of this CustomerEditForm.  # noqa: E501


        :return: The company of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this CustomerEditForm.


        :param company: The company of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._company = company

    @property
    def vat_id(self):
        """Gets the vat_id of this CustomerEditForm.  # noqa: E501


        :return: The vat_id of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._vat_id

    @vat_id.setter
    def vat_id(self, vat_id):
        """Sets the vat_id of this CustomerEditForm.


        :param vat_id: The vat_id of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._vat_id = vat_id

    @property
    def contact(self):
        """Gets the contact of this CustomerEditForm.  # noqa: E501


        :return: The contact of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this CustomerEditForm.


        :param contact: The contact of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._contact = contact

    @property
    def address(self):
        """Gets the address of this CustomerEditForm.  # noqa: E501


        :return: The address of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this CustomerEditForm.


        :param address: The address of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def country(self):
        """Gets the country of this CustomerEditForm.  # noqa: E501


        :return: The country of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this CustomerEditForm.


        :param country: The country of this CustomerEditForm.  # noqa: E501
        :type: str
        """
        if country is None:
            raise ValueError("Invalid value for `country`, must not be `None`")  # noqa: E501

        self._country = country

    @property
    def currency(self):
        """Gets the currency of this CustomerEditForm.  # noqa: E501


        :return: The currency of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this CustomerEditForm.


        :param currency: The currency of this CustomerEditForm.  # noqa: E501
        :type: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501

        self._currency = currency

    @property
    def phone(self):
        """Gets the phone of this CustomerEditForm.  # noqa: E501


        :return: The phone of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this CustomerEditForm.


        :param phone: The phone of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def fax(self):
        """Gets the fax of this CustomerEditForm.  # noqa: E501


        :return: The fax of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._fax

    @fax.setter
    def fax(self, fax):
        """Sets the fax of this CustomerEditForm.


        :param fax: The fax of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._fax = fax

    @property
    def mobile(self):
        """Gets the mobile of this CustomerEditForm.  # noqa: E501


        :return: The mobile of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._mobile

    @mobile.setter
    def mobile(self, mobile):
        """Sets the mobile of this CustomerEditForm.


        :param mobile: The mobile of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._mobile = mobile

    @property
    def email(self):
        """Gets the email of this CustomerEditForm.  # noqa: E501


        :return: The email of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this CustomerEditForm.


        :param email: The email of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def homepage(self):
        """Gets the homepage of this CustomerEditForm.  # noqa: E501


        :return: The homepage of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._homepage

    @homepage.setter
    def homepage(self, homepage):
        """Sets the homepage of this CustomerEditForm.


        :param homepage: The homepage of this CustomerEditForm.  # noqa: E501
        :type: str
        """

        self._homepage = homepage

    @property
    def timezone(self):
        """Gets the timezone of this CustomerEditForm.  # noqa: E501


        :return: The timezone of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this CustomerEditForm.


        :param timezone: The timezone of this CustomerEditForm.  # noqa: E501
        :type: str
        """
        if timezone is None:
            raise ValueError("Invalid value for `timezone`, must not be `None`")  # noqa: E501

        self._timezone = timezone

    @property
    def color(self):
        """Gets the color of this CustomerEditForm.  # noqa: E501


        :return: The color of this CustomerEditForm.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this CustomerEditForm.


        :param color: The color of this CustomerEditForm.  # noqa: E501
        :type: str
        """
        if color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501

        self._color = color

    @property
    def visible(self):
        """Gets the visible of this CustomerEditForm.  # noqa: E501


        :return: The visible of this CustomerEditForm.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this CustomerEditForm.


        :param visible: The visible of this CustomerEditForm.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomerEditForm, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomerEditForm):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
