# coding: utf-8

"""
    Kimai 2 - API Docs

    JSON API for the Kimai 2 time-tracking software. Read more about its usage in the [API documentation](https://www.kimai.org/documentation/rest-api.html) and then download a [Swagger file](doc.json) for import e.g. in Postman. Be aware: it is not yet considered stable and BC breaks might happen.   # noqa: E501

    OpenAPI spec version: 0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ActivityRateForm(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'str',
        'rate': 'float',
        'internal_rate': 'float',
        'is_fixed': 'bool'
    }

    attribute_map = {
        'user': 'user',
        'rate': 'rate',
        'internal_rate': 'internalRate',
        'is_fixed': 'isFixed'
    }

    def __init__(self, user=None, rate=None, internal_rate=None, is_fixed=None):  # noqa: E501
        """ActivityRateForm - a model defined in Swagger"""  # noqa: E501

        self._user = None
        self._rate = None
        self._internal_rate = None
        self._is_fixed = None
        self.discriminator = None

        if user is not None:
            self.user = user
        self.rate = rate
        if internal_rate is not None:
            self.internal_rate = internal_rate
        if is_fixed is not None:
            self.is_fixed = is_fixed

    @property
    def user(self):
        """Gets the user of this ActivityRateForm.  # noqa: E501


        :return: The user of this ActivityRateForm.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this ActivityRateForm.


        :param user: The user of this ActivityRateForm.  # noqa: E501
        :type: str
        """

        self._user = user

    @property
    def rate(self):
        """Gets the rate of this ActivityRateForm.  # noqa: E501

        Rate  # noqa: E501

        :return: The rate of this ActivityRateForm.  # noqa: E501
        :rtype: float
        """
        return self._rate

    @rate.setter
    def rate(self, rate):
        """Sets the rate of this ActivityRateForm.

        Rate  # noqa: E501

        :param rate: The rate of this ActivityRateForm.  # noqa: E501
        :type: float
        """
        if rate is None:
            raise ValueError("Invalid value for `rate`, must not be `None`")  # noqa: E501

        self._rate = rate

    @property
    def internal_rate(self):
        """Gets the internal_rate of this ActivityRateForm.  # noqa: E501

        Internal rate  # noqa: E501

        :return: The internal_rate of this ActivityRateForm.  # noqa: E501
        :rtype: float
        """
        return self._internal_rate

    @internal_rate.setter
    def internal_rate(self, internal_rate):
        """Sets the internal_rate of this ActivityRateForm.

        Internal rate  # noqa: E501

        :param internal_rate: The internal_rate of this ActivityRateForm.  # noqa: E501
        :type: float
        """

        self._internal_rate = internal_rate

    @property
    def is_fixed(self):
        """Gets the is_fixed of this ActivityRateForm.  # noqa: E501


        :return: The is_fixed of this ActivityRateForm.  # noqa: E501
        :rtype: bool
        """
        return self._is_fixed

    @is_fixed.setter
    def is_fixed(self, is_fixed):
        """Sets the is_fixed of this ActivityRateForm.


        :param is_fixed: The is_fixed of this ActivityRateForm.  # noqa: E501
        :type: bool
        """

        self._is_fixed = is_fixed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActivityRateForm, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActivityRateForm):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
